source "https://rubygems.org"

gem "fastlane"
gem "cocoapods", "1.16.2"
gem "abbrev"
gem "base64"
gem "logger"
gem "mutex_m"
gem "bigdecimal"
gem "ostruct"
gem "csv"
gem "drb"
gem "getoptlong"
gem "nkf"
gem "observer"
gem "pstore"
gem "readline"
gem "rexml"
gem "syslog"