// dynamics
export './dynamics/buildingBlocksStability.dart';
export './dynamics/buoyancyAndActionReaction.dart';
export './dynamics/buoyancyComparison.dart';
export './dynamics/elasticCollision1D.dart';
export './dynamics/elasticCollision2D.dart';
export './dynamics/fook.dart';
export './dynamics/freeFall.dart';
export './dynamics/jupiter.dart';
export './dynamics/kineticFriction.dart';
export './dynamics/moonOrbit.dart';
export './dynamics/oneSideLift.dart';
export './dynamics/pendulumPeriodMeasurement.dart';
export './dynamics/planets.dart';
export './dynamics/staticFriction.dart';
export './dynamics/verticalSpringOscillation.dart';
export './dynamics/barometer.dart';
export './dynamics/accelerometer.dart';
export './dynamics/AccelerometerExperimentWidget.dart';
export './dynamics/BarometerExperimentWidget.dart';

// electroMagnetism
export './electroMagnetism/ampereLawTorque.dart';
export './electroMagnetism/bismuthDiamagnetism.dart';
export './electroMagnetism/capacitanceParallelCombination.dart';
export './electroMagnetism/capacitanceSeriesCombination.dart';
export './electroMagnetism/capacitorChargeStorage.dart';
export './electroMagnetism/capacitorIntroduction.dart';
export './electroMagnetism/coilProperties.dart';
export './electroMagnetism/diodeIntroduction.dart';
export './electroMagnetism/forceBetweenParallelCurrents.dart';
export './electroMagnetism/lemonBatteryVoltage.dart';
export './electroMagnetism/lorentzForce.dart';
export './electroMagnetism/magneticFieldCircularLoop.dart';
export './electroMagnetism/solenoidMagneticField.dart';
export './electroMagnetism/neodymiumMagnetFieldMeasurement.dart';
export './electroMagnetism/parallelPlateCapacitanceMeasurement.dart';
export './electroMagnetism/parallelResistance.dart';
export './electroMagnetism/rcCircuit.dart';
export './electroMagnetism/resistanceMeasurement.dart';
export './electroMagnetism/resistanceVsLength.dart';
export './electroMagnetism/resistivityTemperatureDependence.dart';
export './electroMagnetism/seriesResistance.dart';
export './electroMagnetism/solenoidSelfInductance.dart';
export './electroMagnetism/ohmsLaw.dart';
export './electroMagnetism/magnetometer.dart';
export './electroMagnetism/magnetometer.dart';
export './electroMagnetism/MagnetometerExperimentWidget.dart';


// thermoDynamics
export './thermoDynamics/boyle_law.dart';

// waves
export './waves/closedPipeResonance.dart';
export './waves/diffractionGrating.dart';
export './waves/openPipeResonance.swift.dart';
export './waves/spectroscopy.dart';
export './waves/beat.dart';
export './waves/doppler.dart';
export './waves/dopplerObserverMoving.dart';
export './waves/luxMeasurement.dart';
export './waves/LuxMeasurementWidget.dart';
export './waves/frequencyMeasurement.dart';